# Generated by Django 5.1 on 2024-09-01 18:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cricketer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("fname", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.URLField()),
                ("lname", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=100)),
                ("matches", models.IntegerField(blank=True, null=True)),
                ("runs", models.IntegerField(blank=True, null=True)),
                ("average", models.FloatField(blank=True, null=True)),
                ("strike_rate", models.FloatField(blank=True, null=True)),
                ("catches", models.IntegerField(blank=True, null=True)),
                ("story", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
