# Generated by Django 5.1 on 2024-09-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cricketers", "0002_rename_average_cricketer_odi_average_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cricketer",
            name="url_source",
            field=models.URLField(blank=True, null=True),
        ),
    ]
